/*
 * Jakefile
 * BBBlocksKit
 *
 * Created by You on March 24, 2012.
 * Copyright 2012, Your Company All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    blend = require("cappuccino/jake").blend,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";


blend ("BBBlocksKit.blend", function(BBBlocksKitTask)
{
    BBBlocksKitTask.setBuildIntermediatesPath(FILE.join("Build", "BBBlocksKit.build", configuration))
    BBBlocksKitTask.setBuildPath(FILE.join("Build", configuration));

    BBBlocksKitTask.setThemeDescriptors(new FileList("ThemeDescriptors.j"));
    BBBlocksKitTask.setIdentifier("com.280n.com.yourcompany.BBBlocksKit");
    BBBlocksKitTask.setResources(new FileList("Resources/*"));
});

task ("default", ["BBBlocksKit.blend"]);

task ("build", ["default"]);

